### ISSUE TITLE
Lazy package manager virtual text duplication

### ISSUE THREAD

**Issue by kair8m** [ErichDonGubler/lsp_lines.nvim#3]
Hi and thank you for this awesome plugin 😄 . There is an issue with displaying lazy popup window, see the attached screenshot

![Screenshot 2023-06-22 at 00 03 14](https://github.com/ErichDonGubler/lsp_lines.nvim/assets/53782948/ec9dfde9-8f16-4cfe-ae40-6ef34aa44149)

**Comment by ErichDonGubler** [comment]
Hey there! Unfortunately, this is only a mirror of a repository on Sourcehut, and I'm not the original maintainer. I would encourage you to maintain your own fork, and try to upstream a solution.
