### ISSUE TITLE
Change virtual line color

### ISSUE THREAD

**Issue by diniamo** [ErichDonGubler/lsp_lines.nvim#4]
How can I change the color of virtual lines? Or well, only the part where there isn't text. On the example screenshots the color of lines only changes under virtual text, but it's the whole line for me:
![image](https://github.com/ErichDonGubler/lsp_lines.nvim/assets/55629891/1d3fa11f-910b-48d8-92c1-26fbd2e104e9)

**Comment by ErichDonGubler** [comment]
Hey there! I'm not actually the maintainer of this; this is a fork of a repository in SourceHut. I recommend you ask this question in [upstream](https://git.sr.ht/~whynothugo/lsp_lines.nvim).
